import { PortfolioState } from "./types";

const SAMPLE_PRICE_TIMESTAMP = "2024-06-03T13:30:00.000Z";
const MOOMOO_STATEMENT_DATE = "2026-08-31";
const MOOMOO_PRICE_TIMESTAMP = "2026-09-01T00:00:00.000Z";

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
};

export const sampleState: PortfolioState = {
  currency: "USD",
  portfolios: [
    { id: "growth", name: "Growth" },
    { id: "income", name: "Dividend Income" },
    { id: "moomoo", name: "Moomoo" },
  ],
  activePortfolioId: "all",
  transactions: [
    {
      id: "seed-1",
      portfolioId: "growth",
      symbol: "AAPL",
      name: "Apple Inc.",
      type: "BUY",
      date: daysAgo(400),
      quantity: 20,
      price: 165.3,
      fees: 1,
    },
    {
      id: "seed-2",
      portfolioId: "growth",
      symbol: "AAPL",
      name: "Apple Inc.",
      type: "BUY",
      date: daysAgo(180),
      quantity: 10,
      price: 190.5,
      fees: 1,
    },
    {
      id: "seed-3",
      portfolioId: "income",
      symbol: "MSFT",
      name: "Microsoft Corporation",
      type: "BUY",
      date: daysAgo(300),
      quantity: 12,
      price: 330.1,
      fees: 1,
    },
    {
      id: "seed-4",
      portfolioId: "income",
      symbol: "VOO",
      name: "Vanguard S&P 500 ETF",
      type: "BUY",
      date: daysAgo(500),
      quantity: 15,
      price: 380,
      fees: 0,
    },
    {
      id: "seed-5",
      portfolioId: "income",
      symbol: "VOO",
      name: "Vanguard S&P 500 ETF",
      type: "BUY",
      date: daysAgo(60),
      quantity: 5,
      price: 470,
      fees: 0,
    },
    {
      id: "seed-6",
      portfolioId: "growth",
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      type: "BUY",
      date: daysAgo(250),
      quantity: 8,
      price: 450,
      fees: 1,
    },
    {
      id: "seed-7",
      portfolioId: "growth",
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      type: "SELL",
      date: daysAgo(30),
      quantity: 3,
      price: 900,
      fees: 1,
    },
    {
      id: "seed-8",
      portfolioId: "growth",
      symbol: "AAPL",
      name: "Apple Inc.",
      type: "DIVIDEND",
      date: daysAgo(90),
      quantity: 30,
      price: 7.2,
    },
    {
      id: "seed-9",
      portfolioId: "income",
      symbol: "MSFT",
      name: "Microsoft Corporation",
      type: "DIVIDEND",
      date: daysAgo(45),
      quantity: 12,
      price: 8.4,
    },
    {
      id: "seed-10",
      portfolioId: "moomoo",
      symbol: "558.SI",
      name: "UMS Holdings",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 2500,
      price: 2.66,
    },
    {
      id: "seed-11",
      portfolioId: "moomoo",
      symbol: "BN2.SI",
      name: "Valuetronics Holdings",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 2000,
      price: 1.01,
    },
    {
      id: "seed-12",
      portfolioId: "moomoo",
      symbol: "DAVA",
      name: "Endava plc",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 462,
      price: 3.32,
    },
    {
      id: "seed-13",
      portfolioId: "moomoo",
      symbol: "HQ",
      name: "Horizon Quantum Holdings",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 13,
      price: 14.81,
    },
    {
      id: "seed-14",
      portfolioId: "moomoo",
      symbol: "KWEB",
      name: "KraneShares CSI China Internet ETF",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 33,
      price: 25.81,
    },
    {
      id: "seed-15",
      portfolioId: "moomoo",
      symbol: "LIDR",
      name: "AEye Inc",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 216,
      price: 1.15,
    },
    {
      id: "seed-16",
      portfolioId: "moomoo",
      symbol: "MSTY",
      name: "YieldMax MSTR Option Income Strategy ETF",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 0.9886,
      price: 15.35,
    },
    {
      id: "seed-17",
      portfolioId: "moomoo",
      symbol: "MVIS",
      name: "Microvision Inc",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 127,
      price: 1.81,
    },
    {
      id: "seed-18",
      portfolioId: "moomoo",
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 0.1649,
      price: 220.78,
    },
    {
      id: "seed-19",
      portfolioId: "moomoo",
      symbol: "QSI",
      name: "Quantum-Si Inc",
      type: "BUY",
      date: MOOMOO_STATEMENT_DATE,
      quantity: 500,
      price: 0.7659,
    },
  ],
  prices: {
    AAPL: {
      symbol: "AAPL",
      price: 227.5,
      previousClose: 225.1,
      currency: "USD",
      updatedAt: SAMPLE_PRICE_TIMESTAMP,
      source: "manual",
    },
    MSFT: {
      symbol: "MSFT",
      price: 415.2,
      previousClose: 418.0,
      currency: "USD",
      updatedAt: SAMPLE_PRICE_TIMESTAMP,
      source: "manual",
    },
    VOO: {
      symbol: "VOO",
      price: 512.8,
      previousClose: 510.4,
      currency: "USD",
      updatedAt: SAMPLE_PRICE_TIMESTAMP,
      source: "manual",
    },
    NVDA: {
      symbol: "NVDA",
      price: 220.78,
      previousClose: 118.6,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    "558.SI": {
      symbol: "558.SI",
      price: 2.66,
      currency: "SGD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    "BN2.SI": {
      symbol: "BN2.SI",
      price: 1.01,
      currency: "SGD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    DAVA: {
      symbol: "DAVA",
      price: 3.32,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    HQ: {
      symbol: "HQ",
      price: 14.81,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    KWEB: {
      symbol: "KWEB",
      price: 25.81,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    LIDR: {
      symbol: "LIDR",
      price: 1.15,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    MSTY: {
      symbol: "MSTY",
      price: 15.35,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    MVIS: {
      symbol: "MVIS",
      price: 1.81,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
    QSI: {
      symbol: "QSI",
      price: 0.7659,
      currency: "USD",
      updatedAt: MOOMOO_PRICE_TIMESTAMP,
      source: "manual",
    },
  },
  watchlist: [
    { symbol: "GOOGL", name: "Alphabet Inc." },
    { symbol: "AMZN", name: "Amazon.com Inc." },
  ],
  dividendHistory: {},
};
